language: node_js

node_js:
  - node

branches:
  only:
  - master
  - gh-pages
  - /.*/

before_script:
  - npm install -g @angular/cli

script:
  - npm run build-prod

before_deploy:  
  - cd dist
  - tar -czvf ../lorgnette-${TRAVIS_TAG}.tar.gz *
  - cd ..

deploy:
   - provider: firebase
     token:
       secure: $FIREBASE_TOKEN
     skip_cleanup: true     
   - provider: pages
     skip_cleanup: true
     github_token: $GITHUB_TOKEN
     on:
       branch: master
   - provider: releases
     api_key:
      secure: $GITHUB_KEY
     file: "lorgnette-${TRAVIS_TAG}.tar.gz"
     skip_cleanup: true
     on:
       tags: true
   - provider: npm
     email: cedric.elslander@gmail.com
     api_key:
       secure: $NPM_API_KEY
     on:
       tags: true