language: node_js
node_js:
- node
branches:
  only:
  - master
before_script:
- npm install -g firebase-tools
- npm install -g @angular/cli
script:
- ng build --prod --aot
after_success:
- firebase deploy --token $FIREBASE_TOKEN
deploy:
   - provider: pages
     skip_cleanup: true
     github_token: $GITHUB_TOKEN
     on:
       branch: master
   - provider: releases
     api_key:
      secure: 6a90eLUt9K+hkk4okbkQaSP7cmrIivx9SBo672vnSUyiqisRTMhUw7bOMB0xSY5MgO7V8ncaGPyFnRH4fSpQnO3vFLF/kvBp52MBOeqYJYRlfrEsDbntC9jIQl0aL1m6T/FVmWnRdl7CkkZsmhL4sE0UlISPxQaqJudbpJJYboWEuBdLgA0W3lyGzznRATMcj/rWl0gaJ0mIdX6cPmLoCF2/+41prdGItFBOMZw0S+xZ7kzjbRgyn3K4FZc9D3qb4q57dMRkeIkctsrM1rLooQFfDTIZKAhzlHF9Ofx96QlwqA8a9tpvv9I9pp+Jn9Qa+v/FtLM9YBVokkEB/KKKiZrM4eHqTJYF9n26WURFcaWpUuHkVVuODR0UpJmk4a6CbyG2ps26IvzU7TP1jHFQIsSJ3d+ctLZFukjoPo5nrShbeNeLBeX1Sd5C/IRPDHFbL4MuxzTg33zv+Wst4eXRT8+sqEeBxUfjX2gJ2x69m0L0U1NU9Ug3RgCd++F4yiXNhc/HjwZj40+wctoL+zFn7emTiqNkXieHlWWIqxwMPoJWzXZgnn2mADKOCNqIosRWyIFDSkFBxWpImvfn7JdxPbgIZ8a3s3TlBnO036S0R2XhXmzNy0rHFaw199a6FDpkskVK2nV8Hnenp4ijmmMUkfbNhZqD9ESMmX2+QVddc4E=
     file_glob: true
     file: "dist/*"
     skip_cleanup: true
     on:
       tags: true
       all_branches: true
    
